import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dewlish Platinum Celebration</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <h1 className={styles.title}>
            The Queen&apos;s Platinum Jubilee 2022
          </h1>
          <h2 className={styles.headerSubText}>Dewlish Village Celebration</h2>
        </header>
        <section className={styles.section}>
          <p>
            Dewlish will be holding a series of events to celebrate the
            Queen&apos;s Platinum Jublilee over the national bank holiday from
            Thursday 2nd June to Sunday 5th June 2022. We will be running a
            series of fundraising events over the course of the next year to
            fund these events.
          </p>
          <p>
            As of 8th July 2021 this is a new website. We will be adding content
            over the next few weeks, so please bookmark it.
          </p>
        </section>
        <section className={styles.section}>
          <h2 className={styles.subHeading}>Barbecue Sat 31st July 2021</h2>
          <p>
            Our first event will be a barbecue outside the village hall on Sat
            31st July. Starts at 6pm - all welcome.
          </p>
        </section>
      </main>
    </div>
  );
}
